version: '3'
services:
  freeradius:
    build: .
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    #volumes:
    #  - ./mods-available:/etc/freeradius/3.0/mods-available
    #  - ./sites-available:/etc/freeradius/3.0/sites-available
    restart: unless-stopped